VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|  
# Use the same key for each machine  
  config.ssh.insert_key = false
  
  config.vm.define "vagrant1" do |vagrant1|    
	  vagrant1.vm.box = "ubuntu/trusty64"
	  vagrant1.vm.hostname = 'host1'
	  vagrant1.vm.network :private_network, ip: "192.168.56.102"
	  vagrant1.vm.network "forwarded_port", guest: 80, host: 8080    
	  vagrant1.vm.network "forwarded_port", guest: 443, host: 8443
      vagrant1.vm.provision "shell", inline: <<-SHELL
	    apt-get install -y ansible
	  SHELL
  end
  
  config.vm.define "vagrant2" do |vagrant2|    
	  vagrant2.vm.box = "ubuntu/trusty64"
	  vagrant2.vm.hostname = 'host2'
	  vagrant2.vm.network :private_network, ip: "192.168.56.103"
	  vagrant2.vm.network "forwarded_port", guest: 80, host: 8081    
	  vagrant2.vm.network "forwarded_port", guest: 443, host: 8444  
  end
  
  config.vm.define "vagrant3" do |vagrant3|    
	  vagrant3.vm.box = "ubuntu/trusty64"
	  vagrant3.vm.hostname = 'host3'
	  vagrant3.vm.network :private_network, ip: "192.168.56.104"
	  vagrant3.vm.network "forwarded_port", guest: 80, host: 8082    
	  vagrant3.vm.network "forwarded_port", guest: 443, host: 8445  
  end
  
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update -y
	apt-get install -y git
  SHELL
end
